export const types = {
    SAY_HELLO:"SAY_HELLO",
    CLEAR_TEXT:"CLEAR_TEXT",

    CREATE_NUMBER: "CREATE_NUMBER",
    ADD_NAME: "ADD_NAME",
    CLEAR_NAME:"CLEAR_NAME",

    ADD_NUMBER:'ADD_NUMBER'


}
